import type { Grupo, Patron } from './paso-content'

// English copy for PASO. IDs, dimensions and profile codes deliberately match
// the Spanish dataset so language never changes scoring or the final profile.
const GROUP_ROWS: [string, string, string, string][] = [
  ['I decide and move forward', 'I connect with people', 'I take my time', 'I look before I step'],
  ['I stand by what I think', 'I treat people warmly', 'I wait patiently', 'I think it through calmly'],
  ['I am direct', 'I open up to others', 'I keep a steady pace', 'I pay attention to detail'],
  ['I take on difficult things', 'I connect easily', 'I remain steady', 'I notice everything'],
  ['I push through to the end', 'I express myself well', 'I am loyal to my people', 'I work rigorously'],
  ['I do not give up', 'I look on the bright side', 'I stay calm', 'I proceed cautiously'],
  ['I demand a lot of myself', 'I know how to persuade', 'I remain composed', 'I review things before approving them'],
  ['I can rely on myself', 'I get enthusiastic', 'I keep a low profile', 'I keep something back'],
  ['I am brave', 'I say what I feel', 'I am loyal', 'I follow a method'],
  ['I go for it without hesitation', 'I bring joy', 'I do not take myself too seriously', 'I analyse it'],
  ['I move quickly', 'I am sociable', 'I am consistent', 'I proceed with caution'],
  ['I persist until I succeed', 'People tend to like me', 'I am kind', 'I do things in an orderly way'],
  ['I bring energy', 'I have spark', 'People can rely on me', 'I know what is appropriate'],
  ['I aim high', 'I join in with plans', 'I stay calm', 'I strive for precision'],
  ['I approach things eagerly', 'I show myself as I am', 'I do not boast', 'I do not reveal everything'],
  ['I go my own way', 'I speak with ease', 'I try to please', 'I follow a system'],
  ['I decide quickly', 'I encourage others', 'I endure over time', 'I work with care'],
  ['I am effective', 'I am pleasant to be around', 'I take my time', 'I reflect on it'],
  ['I take the lead', 'My feelings are contagious', 'People know what to expect from me', 'I calculate it'],
  ['I lead', 'I get along with everyone', 'I avoid going too far', 'I leave no mistakes'],
  ['I speak plainly', 'I express myself warmly', 'I move with confidence', 'I treat everyone equally'],
  ['I take the initiative', 'I inspire trust', 'I keep a regular pace', 'I am conscientious'],
  ['I move with determination', 'I win people over', 'I stay humble', 'I proceed carefully'],
  ['I do not shrink back', 'I build rapport easily', 'I do not rush', 'I keep my own counsel'],
  ['I speak frankly', 'I treat people kindly', 'I lend a hand', 'I look inward'],
  ['I do not depend on anyone', 'I know how to reach people', 'I move forward calmly', 'I finish things properly'],
  ['I move with strength', 'I am cheerful', 'I look out for others', 'I make sure it is done well'],
  ['I do not quit', 'I inspire others', 'I am patient', 'I see both sides'],
]

export const PASO_GROUPS_EN: Grupo[] = GROUP_ROWS.map((row, index) => ({
  grupo: index + 1,
  P: row[0],
  A: row[1],
  S: row[2],
  O: row[3],
}))

export const PASO_PATTERNS_EN: Patron[] = [
  {
    codigo: 'PPPP', nombre: 'Frontline Walker',
    retrato: 'You walk straight ahead, without detours. While others are still studying the map, you have already taken the first step. Your strength is momentum; your challenge is remembering that some stretches require presence rather than speed.',
    motivacion: 'To arrive, resolve and have something to show at the end of the day. Movement itself proves that life is moving forward.',
    bajo_presion: 'You become more forceful, not slower. You decide quickly and expect others to keep pace.',
    teme: 'Irrelevance. Being unable to move forward or having nothing left to conquer weighs more than failure.',
    seria_mas_eficaz_si: 'You accepted that some stretches of the road call for presence, not speed.',
    libro_recomendado: 'El Ikigai que no te contaron',
  },
  {
    codigo: 'AAAA', nombre: 'Companion Walker',
    retrato: 'You walk towards people. Each step feels different when someone is beside you, and your energy grows with the group. Your gift is bringing people together; your learning is discovering that solitary stretches also belong to you and can sustain you.',
    motivacion: 'For the journey to be shared. An achievement with nobody to celebrate it with barely feels like an achievement.',
    bajo_presion: 'You scatter energy through conversation and validation, sometimes mistaking talking about the problem for solving it.',
    teme: 'The silent road, without witnesses or recognition.',
    seria_mas_eficaz_si: 'You practised sustaining stretches on your own without interpreting solitude as losing direction.',
    libro_recomendado: 'Camina sin separarte de ti',
  },
  {
    codigo: 'SSSS', nombre: 'Steady Walker',
    retrato: 'You walk at a constant pace, without shocks or hurry. Reliability is your terrain: people know you will still be there tomorrow. Your strength is consistency; your challenge is daring to accelerate when the moment truly calls for it.',
    motivacion: 'A steady step without disruption. Reliability is your form of excellence.',
    bajo_presion: 'You withdraw and try to restore familiar order; abrupt change costs you more than effort itself.',
    teme: 'Being forced to change route without warning.',
    seria_mas_eficaz_si: 'You allowed yourself to accelerate when the moment genuinely requires it instead of protecting the pace by default.',
    libro_recomendado: 'Disciplina para indisciplinados',
  },
  {
    codigo: 'OOOO', nombre: 'Observant Walker',
    retrato: 'Before stepping, you look. You study the ground, calculate the route and only then move, because one considered step is worth ten taken blindly. Your gift is clarity; your trap is believing the map can be complete before you begin.',
    motivacion: 'To understand the terrain before stepping on it. One well-calculated step is worth ten blind ones.',
    bajo_presion: 'You retreat into analysis and review once more before deciding; the risk is that the review never ends.',
    teme: 'Making a mistake because you did not look carefully enough.',
    seria_mas_eficaz_si: 'You accepted that no map is complete before the journey and that some terrain can only be known by stepping onto it.',
    libro_recomendado: 'No todo lo que te frena es tuyo',
  },
  {
    codigo: 'PA', nombre: 'Mobilising Walker',
    retrato: 'You move quickly and tend to carry others with your momentum; you rarely walk entirely alone. You need both to arrive and for the distance travelled to be seen. Your strength can move whole groups; your challenge is looking back and asking before pulling.',
    motivacion: 'To move quickly and bring others with you. You need both the result and the applause that accompanies it.',
    bajo_presion: 'You impose the pace without asking and may overwhelm those who walk more slowly.',
    teme: 'The group moving without your drive, or nobody noticing how far you have come.',
    seria_mas_eficaz_si: 'You learned to ask before pulling and to celebrate other people’s progress without needing to lead it.',
    libro_recomendado: 'El Ikigai que no te contaron',
  },
  {
    codigo: 'PO', nombre: 'Calculating Walker',
    retrato: 'You move forward, but only once you understand the ground. You analyse first and then decide quickly. Your gift is joining thought with action; your trap is demanding a perfect analysis that never quite arrives.',
    motivacion: 'To advance, but only after understanding the terrain. Once you have analysed it, you decide quickly.',
    bajo_presion: 'You become distant and abrupt, prioritising effectiveness over anything that might slow it down.',
    teme: 'Acting on incomplete information and having the mistake exposed to everyone.',
    seria_mas_eficaz_si: 'You accepted that perfect analysis does not exist and that walking also means tolerating uncertainty.',
    libro_recomendado: 'No todo lo que te frena es tuyo',
  },
  {
    codigo: 'AS', nombre: 'Nurturing Walker',
    retrato: 'You walk while making sure nobody is left behind. The slowest person sets the pace because the journey feels better in calm company. Your gift is welcoming others; your learning is understanding that supporting someone does not always mean pleasing them.',
    motivacion: 'For nobody to be left behind. The road only makes sense in good company and without hurry.',
    bajo_presion: 'You avoid conflict at all costs, even when saying something uncomfortable would be most useful.',
    teme: 'Breaking the group’s harmony, even if preserving it means leaving something important unsaid.',
    seria_mas_eficaz_si: 'You understood that supporting does not always mean pleasing.',
    libro_recomendado: 'Camina sin separarte de ti',
  },
  {
    codigo: 'SO', nombre: 'Methodical Walker',
    retrato: 'You trust the process more than impulse. A clear route without shortcuts or surprises is safe terrain. Your strength is order; your challenge is improvising when the map no longer describes the ground beneath you.',
    motivacion: 'A clear process without surprises or shortcuts. You trust the system more than impulse.',
    bajo_presion: 'You cling to procedure even when the situation calls for flexibility.',
    teme: 'Chaos: change without a prior structure to support it.',
    seria_mas_eficaz_si: 'You allowed yourself to improvise when the map no longer describes the real terrain.',
    libro_recomendado: 'Disciplina para indisciplinados',
  },
  {
    codigo: 'PS', nombre: 'Unwavering Walker',
    retrato: 'Once you choose a direction, you hold it whatever the cost. Your determination is measured not by speed but by refusing to drift. That persistence is your strength; your trap is confusing staying the course with refusing to look at the map again.',
    motivacion: 'To reach the destination without deviating, whatever the cost. Determination—not speed—is your strength.',
    bajo_presion: 'You close around one direction and struggle to reconsider even when the terrain has changed.',
    teme: 'Having invested effort in the wrong road and being forced to acknowledge it.',
    seria_mas_eficaz_si: 'You distinguished perseverance from stubbornness: holding a course is not the same as refusing to reconsider the map.',
    libro_recomendado: 'Disciplina para indisciplinados',
  },
  {
    codigo: 'AO', nombre: 'Companion Observer',
    retrato: 'You look at people before the terrain. You listen, observe and process quietly before speaking because understanding the person beside you is your compass. Your gift is perceptiveness; your challenge is sharing what you see before it is fully verified.',
    motivacion: 'To understand the people around you deeply, more than the terrain itself. You listen before offering an opinion.',
    bajo_presion: 'You retreat and process in silence, appearing distant just when your closeness is most needed.',
    teme: 'Misreading someone important, or being misunderstood without a chance to explain.',
    seria_mas_eficaz_si: 'You trusted yourself to share a first impression even before it is fully verified.',
    libro_recomendado: 'Camina sin separarte de ti',
  },
  {
    codigo: 'PAO', nombre: 'Strategic Walker',
    retrato: 'You move with others, but along a route you have already studied. You combine drive, relationships and calculation, and often take charge with a plan in hand. Your gift is leading with judgement; your challenge is making room for a plan that is not yours.',
    motivacion: 'To advance with others, but only along a route already studied. You combine drive, relationships and calculation.',
    bajo_presion: 'You take command with a plan already drawn, though you do not always consult the group first.',
    teme: 'The group losing direction through a lack of clear leadership.',
    seria_mas_eficaz_si: 'You made room for a plan other than your own and trusted that the group can also read the terrain.',
    libro_recomendado: 'El Ikigai que no te contaron',
  },
  {
    codigo: 'ASO', nombre: 'Process-Keeper Walker',
    retrato: 'You walk so the whole group arrives, with each step taken carefully and nobody forced to run. You care for pace and process equally. Your gift is ensuring nobody gets lost; your learning is seeing that sometimes caring well also means moving forward.',
    motivacion: 'For the whole group to arrive, with each step taken well and nobody forced to run.',
    bajo_presion: 'You slow down even further to leave nobody behind, even when the situation calls for movement.',
    teme: 'Your care being mistaken for slowness, or someone feeling excluded from the journey.',
    seria_mas_eficaz_si: 'You accepted that caring well sometimes means advancing, not only waiting.',
    libro_recomendado: 'No todo lo que te frena es tuyo',
  },
  {
    codigo: 'PAS', nombre: 'Driving Walker',
    retrato: 'You keep the group moving with energy, closeness and rhythm—without stopping or burning anyone out. You decide as you go and review later. Your strength is sustaining momentum; your challenge is pausing to think before pushing, not afterwards.',
    motivacion: 'For the group to move steadily without stopping or burning anyone out. You combine drive, closeness and sustained rhythm.',
    bajo_presion: 'You push energetically but save the analysis for later, deciding first and reviewing as you go.',
    teme: 'The group losing cohesion by moving too fast, or losing momentum because you stopped to think too much.',
    seria_mas_eficaz_si: 'You paused before pushing: urgency to keep the group together can prevent you from seeing that the direction is wrong.',
    libro_recomendado: 'Camina sin separarte de ti',
  },
  {
    codigo: 'PSO', nombre: 'Sure-Footed Walker',
    retrato: 'You advance steadily, neither rushing nor stopping, always on tested ground. Your method is your rock. Your strength is solidity; your trap is becoming inflexible precisely when the method itself needs to change.',
    motivacion: 'To advance steadily, without hurry but without stopping, always over tested ground.',
    bajo_presion: 'You become inflexible, trusting your method so much that admitting it may need to change becomes difficult.',
    teme: 'Careless mistakes, and the chaos that would break your system for moving forward.',
    seria_mas_eficaz_si: 'You accepted small doses of improvisation as a legitimate part of the road, not as a failure of the plan.',
    libro_recomendado: 'Disciplina para indisciplinados',
  },
  {
    codigo: 'PASO', nombre: 'Balanced Walker',
    retrato: 'No single dimension leads the others: you decide, accompany, sustain and observe according to what each moment asks. You have no single default mode because all four are available. Your gift is versatility; your challenge is trusting that adaptability is already a strength.',
    motivacion: 'No dimension clearly dominates: you decide, accompany, sustain and observe according to the moment rather than a fixed pattern.',
    bajo_presion: 'You respond with the energy the situation needs, though you may hesitate a little longer because no default mode takes over.',
    teme: 'Losing your ability to adapt and becoming trapped in one way of walking.',
    seria_mas_eficaz_si: 'You trusted that versatility is a strength in itself, not something to compensate for because you lack a single defined type.',
    libro_recomendado: 'No single title stands out: this profile benefits most from seeing the complete method',
  },
]
